 T=1;Tt=20;Tz=50;R=1000;
 [xt,y]=funtrackinglinecircle(T,Tt,Tz,R);
 plot(y(1,:),y(2,:))
 xlabel('横轴模拟数据')
 ylabel('纵轴模拟数据')
 figure
 subplot(2,1,1),plot(xt,y(1,:))
 xlabel('t');ylabel('横轴模拟数据')
 subplot(2,1,2),plot(xt,y(2,:))
 xlabel('t');ylabel('纵轴模拟数据')